# Generated by Django 4.1.6 on 2023-02-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pays',
            name='code_pays',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pays',
            name='nom_pays',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pays',
            name='specification_pays',
            field=models.CharField(max_length=200),
        ),
    ]
