# Generated by Django 4.1.6 on 2023-02-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pays_code_pays_alter_pays_nom_pays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pays',
            name='code_pays',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='pays',
            name='nom_pays',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pays',
            name='specification_pays',
            field=models.CharField(default='Etrangers', max_length=30),
        ),
    ]
