# Generated by Django 4.1.6 on 2023-02-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pays_code_pays_alter_pays_nom_pays_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brevets',
            name='nombre_brevets',
        ),
        migrations.RemoveField(
            model_name='brevets',
            name='voie_brevets',
        ),
        migrations.AddField(
            model_name='brevets',
            name='nombre_cp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='brevets',
            name='nombre_pct',
            field=models.IntegerField(default=0),
        ),
    ]
