# Generated by Django 4.1.6 on 2023-02-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_brevets_nombre_brevets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dmi',
            old_name='annee_DMI',
            new_name='annee_dmi',
        ),
        migrations.RenameField(
            model_name='dmi',
            old_name='nombre_DMI',
            new_name='nombre_dmi',
        ),
        migrations.RenameField(
            model_name='dmi',
            old_name='type_DMI',
            new_name='type_dmi',
        ),
    ]
