# Generated by Django 4.1.6 on 2023-02-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_annee_dmi_dmi_annee_dmi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dmi',
            old_name='pays_DMI',
            new_name='pays_dmi',
        ),
    ]
