# Generated by Django 4.1.6 on 2023-07-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_historique_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='annee',
            field=models.IntegerField(default=2000),
        ),
    ]
