# Generated by Django 4.1.6 on 2023-07-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_historique_annee'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='upload_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
